---
- hosts: proxmox
  remote_user: root
    vars:
    cdrom: '{"ide0":"local:iso/CentOS-7-x86_64-Minimal-1804.iso,media=cdrom"}'
    network: '{"net0":"virtio,bridge=vmbr0"}'
    disk: '{"virtio0":"WD4T:200"}'
    cores: 1
    vcpus: 2
    node: "home"
  tasks:
  - name: test proxmox_kvm
    proxmox_kvm:
      api_user    : "{{ api_username }}"
      api_password: "{{ api_password }}"
      api_host    : "{{ api_host }}"
      vmid        : 112
      node        : "home"
      ide         : "{{ isofile }}"
      net         : '{"net0":"virtio,bridge=vmbr0"}'
      virtio      : '{"virtio0":"WD4T:200"}'
      cores       : 1
      vcpus       : 2
      # update      : yes
      state       : present
  roles:
    - { role: yimeng.proxmox}
      #    - { role: yimeng.proxmox,state: "present"}
      #- { role: yimeng.proxmox,vm_id: "200",state: "present"}
      #- { role: yimeng.proxmox,vm_id: "111",state: "absent"}
      #- { role: yimeng.proxmox,vm_id: "200",state: "absent"}

