---
- hosts: proxmox
  remote_user: root
  tasks:
  - name: test proxmox_kvm
    proxmox_kvm:
      api_user    : "{{ api_username }}"
      api_password: "{{ api_password }}"
      api_host    : "{{ api_host }}"
      vmid        : 112
      node        : "home"
      ide         : '{"ide0":"local:iso/CentOS-7-x86_64-Minimal-1804.iso,media=cdrom"}'
      net         : '{"net0":"virtio,bridge=vmbr0"}'
      virtio      : '{"virtio0":"WD4T:200"}'
      cores       : 1 
      vcpus       : 2 
      # update      : yes
      state       : present
